# Generated by Django 5.1.2 on 2024-11-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sentence_length', models.IntegerField(help_text='Length of sentence in years')),
                ('rehabilitation_option', models.BooleanField(default=False)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminal')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.memory')),
            ],
        ),
    ]
